from micropython import const

DEFAULT_FRONT_COLOR = const(0)
DEFAULT_BG_COLOR = const(1)
DIALOG_PT = const(2)
DROPDOWN_FOCUS_FRONT_COLOR = const(3)
DROPDOWN_FOCUS_BG_COLOR = const(4)
DROPDOWN_NO_FOCUS_FRONT_COLOR = const(5)
DROPDOWN_NO_FOCUS_BG_COLOR = const(6)
BUTTON_DISABLE_FRONT_COLOR = const(7)
BUTTON_DISABLE_BG_COLOR = const(8)
BUTTON_FOCUS_FRONT_COLOR = const(9)
BUTTON_FOCUS_BG_COLOR = const(10)
BUTTON_NO_FOCUS_FRONT_COLOR = const(11)
BUTTON_NO_FOCUS_BG_COLOR = const(12)
CHECKBOX_FOCUS_FRONT_COLOR = const(13)
CHECKBOX_FOCUS_BG_COLOR = const(14)
RADIOBUTTON_FOCUS_FRONT_COLOR = const(15)
RADIOBUTTON_FOCUS_BG_COLOR = const(16)
LISTBOX_FOCUS_FRONT_COLOR = const(17)
LISTBOX_FOCUS_BG_COLOR = const(18)
LISTBOX_NO_FOCUS_FRONT_COLOR = const(19)
LISTBOX_NO_FOCUS_BG_COLOR = const(20)
TEXTENTRY_JUST_START_FONT_COLOR = const(21)
TEXTENTRY_NO_JUST_START_FONT_COLOR = const(22)
TEXTENTRY_BG_COLOR = const(23)
MULTIENTRY_FRONT_COLOR = const(24)
MULTIENTRY_BG_COLOR = const(25)
MANUBAR_FRONT_COLOR = const(26)
MANUBAR_BG_COLOR = const(27)
MANUBOX_FRONT_COLOR = const(28)
MANUBOX_BG_COLOR = const(29)


picotui_style={
    DEFAULT_FRONT_COLOR : 0,
    DEFAULT_BG_COLOR : 7,
    DIALOG_PT :" ",#\xb1
    DROPDOWN_FOCUS_FRONT_COLOR:7,
    DROPDOWN_FOCUS_BG_COLOR:6,
    DROPDOWN_NO_FOCUS_FRONT_COLOR:0,
    DROPDOWN_NO_FOCUS_BG_COLOR:6,
    BUTTON_DISABLE_FRONT_COLOR:7,
    BUTTON_DISABLE_BG_COLOR:7,
    BUTTON_FOCUS_FRONT_COLOR:7,
    BUTTON_FOCUS_BG_COLOR: 2,
    BUTTON_NO_FOCUS_FRONT_COLOR: 0,
    BUTTON_NO_FOCUS_BG_COLOR:2,
    CHECKBOX_FOCUS_FRONT_COLOR : 4,
    CHECKBOX_FOCUS_BG_COLOR : None,
    RADIOBUTTON_FOCUS_FRONT_COLOR :4,
    RADIOBUTTON_FOCUS_BG_COLOR : None,
    LISTBOX_FOCUS_FRONT_COLOR:7,
    LISTBOX_FOCUS_BG_COLOR:2,
    LISTBOX_NO_FOCUS_FRONT_COLOR:0,
    LISTBOX_NO_FOCUS_BG_COLOR:2,
    TEXTENTRY_JUST_START_FONT_COLOR:7,
    TEXTENTRY_NO_JUST_START_FONT_COLOR:0,
    TEXTENTRY_BG_COLOR :6,
    MULTIENTRY_FRONT_COLOR :0,
    MULTIENTRY_BG_COLOR :6,
    MANUBAR_FRONT_COLOR :7,
    MANUBAR_BG_COLOR :0,
    MANUBOX_FRONT_COLOR :7,
    MANUBOX_BG_COLOR :0,

}