from micropython import const

DEFAULT_FRONT_COLOR = const(0)
DEFAULT_BG_COLOR = const(1)
DIALOG_PT = const(2)
DROPDOWN_FOCUS_FRONT_COLOR = const(3)
DROPDOWN_FOCUS_BG_COLOR = const(4)
DROPDOWN_NO_FOCUS_FRONT_COLOR = const(5)
DROPDOWN_NO_FOCUS_BG_COLOR = const(6)
BUTTON_DISABLE_FRONT_COLOR = const(7)
BUTTON_DISABLE_BG_COLOR = const(8)
BUTTON_FOCUS_FRONT_COLOR = const(9)
BUTTON_FOCUS_BG_COLOR = const(10)
BUTTON_NO_FOCUS_FRONT_COLOR = const(11)
BUTTON_NO_FOCUS_BG_COLOR = const(12)
CHECKBOX_FOCUS_FRONT_COLOR = const(13)
CHECKBOX_FOCUS_BG_COLOR = const(14)
RADIOBUTTON_FOCUS_FRONT_COLOR = const(15)
RADIOBUTTON_FOCUS_BG_COLOR = const(16)


picotui_style={
    DEFAULT_FRONT_COLOR : 0,
    DEFAULT_BG_COLOR : 7,
    DIALOG_PT :" ",#\xb1
    DROPDOWN_FOCUS_FRONT_COLOR:7,
    DROPDOWN_FOCUS_BG_COLOR:6,
    DROPDOWN_NO_FOCUS_FRONT_COLOR:0,
    DROPDOWN_NO_FOCUS_BG_COLOR:6,
    BUTTON_DISABLE_FRONT_COLOR:7,
    BUTTON_DISABLE_BG_COLOR:7,
    BUTTON_FOCUS_FRONT_COLOR:7,
    BUTTON_FOCUS_BG_COLOR: 2,
    BUTTON_NO_FOCUS_FRONT_COLOR: 0,
    BUTTON_NO_FOCUS_BG_COLOR:2,
    CHECKBOX_FOCUS_FRONT_COLOR : 4,
    CHECKBOX_FOCUS_BG_COLOR : None,
    RADIOBUTTON_FOCUS_FRONT_COLOR :4,
    RADIOBUTTON_FOCUS_BG_COLOR : None,

}